[package]
name = "rustjack"
version = "0.2.0"
edition = "2024"

[dependencies]
rand = "0.9.2"
ratatui = "0.30.0"
tokio = { version = "1.32.0", features = ["full"] }
tokio-util = "0.7.9"
crossterm = { version = "0.29.0", features = ["events"] }
