name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    outputs:
      hash: ${{ steps.calc_hash.outputs.hash }}
      version: ${{ steps.get_version.outputs.version }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: x86_64-apple-darwin

    steps:
      - uses: actions/checkout@v4

      - name: Get version
        id: get_version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build Release
        run: cargo build --release --target ${{ matrix.target }}

      - name: Archive Binary
        run: |
          cd target/${{ matrix.target }}/release
          tar -czf ../../../rustjack-${{ matrix.target }}.tar.gz rustjack
          cd ../../../

      - name: Calculate Hash
        id: calc_hash
        run: |
          echo "hash=$(shasum -a 256 rustjack-${{ matrix.target }}.tar.gz | awk '{print $1}')" >> $GITHUB_OUTPUT

      - name: Upload Artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: rustjack-*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}

  update-tap:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Update Homebrew Tap
        uses: mislav/bump-homebrew-formula-action@v3
        with:
          formula-name: rustjack
          homebrew-tap: johncuba/homebrew-tap
          base-branch: main
          tag-name: ${{ github.ref_name }}
          version: ${{ steps.get_version.outputs.version }}
          download-url: https://github.com/johncuba/rustjack/releases/download/${{ github.ref_name }}/rustjack-x86_64-apple-darwin.tar.gz
          download-sha256: ${{ needs.build.outputs.hash }}
        env:
          COMMITTER_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
